name: Build liberator and deploy CRDs

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.15
    steps:
      - uses: actions/checkout@v1
      - name: go test
        run: go test ./...

  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Commit CRDs to nais-yaml
      env:
        DEPLOY_KEY: ${{ secrets.NAIS_YAML_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        mkdir -p $NAIS_YAML
        git clone git@github.com:navikt/nais-yaml.git $NAIS_YAML
        cat config/crd/bases/*.yaml > $NAIS_YAML/templates/zz-generated-nais-crds.yaml
        cd $NAIS_YAML
        git config user.email "aura@nav.no"
        git config user.name "NAIS deploy pipeline"
        git add .
        git --no-pager diff --cached
        git commit -a -m "Update NAIS custom resource definitions\n\nliberator commit sha: ${GITHUB_SHA}"
        git push